# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef236c5f2e3c86b2281ba3226f2bd52524bf76f04d0a7508fe45a7b5e6e0787a124d0f921218e3db653aa41cd3e7120769b1c176ad0091f7e043a8ff00ba815e

test:
  secret_key_base: 02133e507d8dd68938e984994d5b82550019d071c0c3999382786d569e17057f0d94434dd26c91f21912ca036d55c3f32bbdf69e126337c5ba8a3c9db7542db6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
